name: ci

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install web dependencies
        working-directory: apps/web
        run: |
          pnpm install --frozen-lockfile

      - name: Build web app
        working-directory: apps/web
        run: |
          pnpm build

      - name: Install API dependencies
        working-directory: apps/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint API code
        working-directory: apps/api
        run: |
          python -c "import sys; print('Python version:', sys.version)"
          python -c "import fastapi; print('FastAPI imported successfully')"

      - name: Type check shared package
        working-directory: packages/shared
        run: |
          npm install -g typescript
          tsc --noEmit
